### ISSUE TITLE
modinfo.lua version & Steam mismatch

### ISSUE THREAD

**Issue by kzarius** [noerK/DST_mod_more_armor#1]
Hi I was hoping you could update the modinfo.lua version to 1.0.2/1.0.2.1 to reflect the steam workshop version # (1.0.2 instead of 1.0.1b) for us using update scripts to auto-check if there is an update. I would have made a pull request but the recent changes haven't made their way on github yet.

Thanks so much, awesome mod.

**Comment by noerK** [comment]
just pushed the new version also here - did this solve your problem?

**Comment by kzarius** [comment]
my apologies, after removing the directory & revalidating, it is indeed 1.0.2.
